name: active_ecommerce_flutter
description: Flutter mobile application for Active Ecommerce CMS
publish_to: none
version: 7.1.1+73

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core
  http: ^1.2.0
  provider: ^6.1.2
  json_annotation: ^4.9.0
  logging: ^1.2.0

  # Connectivity
  connectivity_plus: ^6.0.3

  # UI & Utils
  shimmer: ^3.0.0
  bordered_text: ^2.0.0
  flutter_html: ^3.0.0-beta.2
  flutter_svg: ^2.0.9
  url_launcher: ^6.3.0
  shared_preferences: ^2.3.2
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  cached_network_image: ^3.4.1
  google_fonts: ^6.2.1
  intl: ^0.19.0
  expandable: ^5.0.1
  dropdown_search: ^6.0.1
  flutter_rating_bar: ^4.0.1
  badges: ^3.1.2
  # flutter_spinkit: ^5.2.0
  flutter_spinkit: 5.1.0

  flutter_staggered_grid_view: ^0.7.0
  photo_view: ^0.15.0
  flip_card: ^0.7.0
  google_maps_flutter: ^2.7.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  image_picker: ^1.1.2

  # Auth & Social
  flutter_facebook_auth: ^7.1.2
  google_sign_in: ^6.2.1
  twitter_login: 
    path: ./plugins/twitter_login
  sign_in_with_apple: ^7.0.1
  share_plus: ^10.0.2

  # Firebase
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  flutter_local_notifications: ^19.4.1

  # Others
  crypto: ^3.0.3
  validators: ^3.0.0
  flutter_typeahead: ^5.2.0
  flutter_downloader: ^1.11.6
  location: ^7.0.1
  shared_value: ^3.0.0
  # font_awesome_flutter: ^10.7.0
  font_awesome_flutter: 10.6.0


  toast: any
  flutter_countdown_timer: any
  route_transitions: any
  intl_phone_field: any
  google_maps_place_picker_mb: any
  timeline_tile: any
  webview_flutter: ^4.2.2 
  intl_phone_number_input: any
  flutter_chat_bubble: any
  package_info_plus: ^4.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.14.1
  change_app_package_name: ^1.1.0

flutter_icons:
  android: true
  ios: true
  image_path: assets/app_logo.png

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - dummy_assets/

flutter_gen:
  output: lib/gen/

flutter_intl:
  enabled: true
